### ISSUE TITLE
v0.0.5 Crashes

### ISSUE THREAD

**Issue by searchy2** [Mursaat/AnimatedGradientTextView#4]
Thanks for making the gradient animation pause when not visible! Unfortunately, the changes cause my app to crash. I believe commit b15663fe72bb5d0430945ea36929ad6ec2f9bf13 is the culprit.

Whenever I open an activity with AnimatedGradientTextView, the following error immediately occurs:
```
java.lang.IllegalArgumentException
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:566)
                                                                       at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:658)
                                                                       at com.mursaat.extendedtextview.GradientManager.startGradient(GradientManager.java:173)
                                                                       at com.mursaat.extendedtextview.AnimatedGradientTextView.onSizeChanged(AnimatedGradientTextView.java:36)
```
What might be causing the problem?

**Comment by searchy2** [comment]
Could it be that getScaleX and getScaleY on a view that has not been instantiated is causing the exception?

**Comment by Mursaat** [comment]
I've made some modifications in v0.0.6 but I'm not sure if that will fix your problem.

If maxFPS attribute was not defined on the TextView, then the default value was set to -1 instead of 24. drawTimeInterval became negative, and scheduleAtFixedRate was called with a negative rate.

**Comment by searchy2** [comment]
Ah yes, I did not set maxFPS in XML. :P 
I'll test and :crossed_fingers:  the issue is fixed!

**Comment by searchy2** [comment]
WAHOOO! You did it :) 
God bless!

**Comment by Mursaat** [comment]
🙂
